/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[18];
new Text:cheater20;
new Text:cheater19;
new Text:cheater18;

//Textdraws
PublicTD[0] = TextDrawCreate(500.000000, 279.000000, "John_Mrucznik - 15");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[0], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -16776961);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 1);

cheater20 = TextDrawCreate(500.000000, 114.000000, "John_Mrucznik - 0");
TextDrawFont(cheater20, 1);
TextDrawLetterSize(cheater20, 0.137500, 0.900000);
TextDrawTextSize(cheater20, 607.500000, 17.000000);
TextDrawSetOutline(cheater20, 1);
TextDrawSetShadow(cheater20, 0);
TextDrawAlignment(cheater20, 1);
TextDrawColor(cheater20, -16776961);
TextDrawBackgroundColor(cheater20, 255);
TextDrawBoxColor(cheater20, 50);
TextDrawUseBox(cheater20, 1);
TextDrawSetProportional(cheater20, 1);
TextDrawSetSelectable(cheater20, 1);

cheater19 = TextDrawCreate(500.000000, 125.000000, "John_Mrucznik - 1");
TextDrawFont(cheater19, 1);
TextDrawLetterSize(cheater19, 0.137500, 0.900000);
TextDrawTextSize(cheater19, 607.500000, 17.000000);
TextDrawSetOutline(cheater19, 1);
TextDrawSetShadow(cheater19, 0);
TextDrawAlignment(cheater19, 1);
TextDrawColor(cheater19, -16776961);
TextDrawBackgroundColor(cheater19, 255);
TextDrawBoxColor(cheater19, 50);
TextDrawUseBox(cheater19, 1);
TextDrawSetProportional(cheater19, 1);
TextDrawSetSelectable(cheater19, 1);

cheater18 = TextDrawCreate(500.000000, 136.000000, "John_Mrucznik - 2");
TextDrawFont(cheater18, 1);
TextDrawLetterSize(cheater18, 0.137500, 0.900000);
TextDrawTextSize(cheater18, 607.500000, 17.000000);
TextDrawSetOutline(cheater18, 1);
TextDrawSetShadow(cheater18, 0);
TextDrawAlignment(cheater18, 1);
TextDrawColor(cheater18, -16776961);
TextDrawBackgroundColor(cheater18, 255);
TextDrawBoxColor(cheater18, 50);
TextDrawUseBox(cheater18, 1);
TextDrawSetProportional(cheater18, 1);
TextDrawSetSelectable(cheater18, 1);

PublicTD[1] = TextDrawCreate(500.000000, 147.000000, "John_Mrucznik - 3");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[1], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -16776961);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 1);

PublicTD[2] = TextDrawCreate(500.000000, 158.000000, "John_Mrucznik - 4");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[2], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -16776961);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 1);

PublicTD[3] = TextDrawCreate(500.000000, 169.000000, "John_Mrucznik - 5");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[3], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -16776961);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 1);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 1);

PublicTD[4] = TextDrawCreate(500.000000, 180.000000, "John_Mrucznik - 6");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[4], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 1);
TextDrawColor(PublicTD[4], -16776961);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 1);

PublicTD[5] = TextDrawCreate(500.000000, 191.000000, "John_Mrucznik - 7");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[5], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], -16776961);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 1);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 1);

PublicTD[6] = TextDrawCreate(500.000000, 202.000000, "John_Mrucznik - 8");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[6], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -16776961);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 1);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 1);

PublicTD[7] = TextDrawCreate(500.000000, 213.000000, "John_Mrucznik - 9");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[7], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -16776961);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 1);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 1);

PublicTD[8] = TextDrawCreate(500.000000, 224.000000, "John_Mrucznik - 10");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[8], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -16776961);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 1);

PublicTD[9] = TextDrawCreate(500.000000, 235.000000, "John_Mrucznik - 11");
TextDrawFont(PublicTD[9], 1);
TextDrawLetterSize(PublicTD[9], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[9], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -2686721);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 1);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 1);

PublicTD[10] = TextDrawCreate(500.000000, 246.000000, "John_Mrucznik - 12");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[10], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[10], 1);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -16776961);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 1);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 1);

PublicTD[11] = TextDrawCreate(500.000000, 257.000000, "John_Mrucznik - 13");
TextDrawFont(PublicTD[11], 1);
TextDrawLetterSize(PublicTD[11], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[11], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[11], 1);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 1);
TextDrawColor(PublicTD[11], -16776961);
TextDrawBackgroundColor(PublicTD[11], 255);
TextDrawBoxColor(PublicTD[11], 50);
TextDrawUseBox(PublicTD[11], 1);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 1);

PublicTD[12] = TextDrawCreate(500.000000, 268.000000, "John_Mrucznik - 14");
TextDrawFont(PublicTD[12], 1);
TextDrawLetterSize(PublicTD[12], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[12], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[12], 1);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 1);
TextDrawColor(PublicTD[12], -16776961);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], 50);
TextDrawUseBox(PublicTD[12], 1);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 1);

PublicTD[13] = TextDrawCreate(500.000000, 290.000000, "John_Mrucznik - 16");
TextDrawFont(PublicTD[13], 1);
TextDrawLetterSize(PublicTD[13], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[13], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[13], 1);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], -16776961);
TextDrawBackgroundColor(PublicTD[13], 255);
TextDrawBoxColor(PublicTD[13], 50);
TextDrawUseBox(PublicTD[13], 1);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 1);

PublicTD[14] = TextDrawCreate(500.000000, 301.000000, "John_Mrucznik - 17");
TextDrawFont(PublicTD[14], 1);
TextDrawLetterSize(PublicTD[14], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[14], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[14], 1);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 1);
TextDrawColor(PublicTD[14], -16776961);
TextDrawBackgroundColor(PublicTD[14], 255);
TextDrawBoxColor(PublicTD[14], 50);
TextDrawUseBox(PublicTD[14], 1);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 1);

PublicTD[15] = TextDrawCreate(500.000000, 312.000000, "John_Mrucznik - 18");
TextDrawFont(PublicTD[15], 1);
TextDrawLetterSize(PublicTD[15], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[15], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[15], 1);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 1);
TextDrawColor(PublicTD[15], -16776961);
TextDrawBackgroundColor(PublicTD[15], 255);
TextDrawBoxColor(PublicTD[15], 50);
TextDrawUseBox(PublicTD[15], 1);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 1);

PublicTD[16] = TextDrawCreate(500.000000, 323.000000, "John_Mrucznik - 19");
TextDrawFont(PublicTD[16], 1);
TextDrawLetterSize(PublicTD[16], 0.137500, 0.900000);
TextDrawTextSize(PublicTD[16], 607.500000, 17.000000);
TextDrawSetOutline(PublicTD[16], 1);
TextDrawSetShadow(PublicTD[16], 0);
TextDrawAlignment(PublicTD[16], 1);
TextDrawColor(PublicTD[16], -1061109505);
TextDrawBackgroundColor(PublicTD[16], 255);
TextDrawBoxColor(PublicTD[16], 50);
TextDrawUseBox(PublicTD[16], 1);
TextDrawSetProportional(PublicTD[16], 1);
TextDrawSetSelectable(PublicTD[16], 1);

PublicTD[17] = TextDrawCreate(519.000000, 102.000000, "Szkodnicy:");
TextDrawFont(PublicTD[17], 1);
TextDrawLetterSize(PublicTD[17], 0.191666, 0.900000);
TextDrawTextSize(PublicTD[17], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[17], 1);
TextDrawSetShadow(PublicTD[17], 0);
TextDrawAlignment(PublicTD[17], 2);
TextDrawColor(PublicTD[17], -1);
TextDrawBackgroundColor(PublicTD[17], 255);
TextDrawBoxColor(PublicTD[17], 50);
TextDrawUseBox(PublicTD[17], 0);
TextDrawSetProportional(PublicTD[17], 1);
TextDrawSetSelectable(PublicTD[17], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
