/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <progress2>
//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerBar:PlayerProgressBar[MAX_PLAYERS][1];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerProgressBar[playerid][0] = CreatePlayerProgressBar(playerid, 548.000000, 34.000000, 62.500000, 5.500000, -293409025, 20.000000, 0);
	SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][0], 10.000000);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	DestroyPlayerProgressBar(playerid, PlayerProgressBar[playerid][0]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		ShowPlayerProgressBar(playerid, PlayerProgressBar[playerid][0]);
		return 1;
	}
	return 0;
}
