CREATE TABLE IF NOT EXISTS `mru_kontakty` (
`UID` int(11) NOT NULL,
  `Owner` int(11) NOT NULL,
  `Number` int(11) NOT NULL,
  `Name` varchar(32) CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10542 DEFAULT CHARSET=latin1;


ALTER TABLE `mru_kontakty`
 ADD PRIMARY KEY (`UID`);


ALTER TABLE `mru_kontakty`
MODIFY `UID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=10542;