
CREATE TABLE IF NOT EXISTS `mru_nazwyrang` (
  `ID` int(11) NOT NULL,
  `typ` int(11) NOT NULL COMMENT '1 - frakcja 2 - rodzina',
  `rangi` varchar(256) COLLATE utf8_polish_ci NOT NULL COMMENT 'Skompresowane nazwy rang'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

ALTER TABLE `mru_nazwyrang`
 ADD PRIMARY KEY (`ID`,`typ`), ADD KEY `ID` (`ID`);

INSERT INTO `mru_nazwyrang` (`ID`, `typ`, `rangi`) VALUES
(0, 1, '-, -, Senior Special Agent, Senior Special Agent, Senior Special Agent, Assistant Agent I.C., Dyrektor ds finansow, Kierownik Korporacji, Deputy TSU Commander, Senior Special Agent'),
(0, 2, 'Rosenberg Industries, Starszy wolontariusz, Pracownik Kancelarii, Opiekun porz¹dkowych, Operations Agent III, Intelligence Agent I, Dowodz¹cy kurwido³ka, Prokurator Generalny, Zastêpca Gubernatora, -'),
(1, 1, 'Cadet LSPD, Police Officer I, Police Officer II, Police Officer III, Sergeant I, Sergeant II, Lieutenant, Captain, Commander, Chief of Police'),
(1, 2, 'Stażysta, Aplikant, Radca Prawny, Komornik, Prokurator, Sędzia, Sędzia Stanowy, Sędzia Najwyższy, Z-ca Prezesa, Prezes Sądu'),
(2, 1, '-, New Agent Trainee, Agent, Special Agent, Senior Agent, Supervisory Agent, Spec. Agent I.C., Associate Director, Deputy Director, Director'),
(2, 2, 'Solapa, Dealer, Fresh Member, Aztecas Member, Loco Gangster, Boss Protector, Boss Guardian, Drogas Baron, BOSS Right Hand, BOSS'),
(3, 1, 'DSG, Private, Private First Class, Specialist, Corporal, Sergeant, Staff Sergeant, First Sergeant, Sergeant Major, Comm. Ser. Major'),
(3, 2, 'Mechanic, Newbie, Young Rider, Rider, Ghost Rider, Right Hand, Boss, -, -, -'),
(4, 1, 'Candidate, Probationary FF, EMT, Firefighter, Paramedic F.C, FF Engineer, Paramedic I.C, Chief of Staff, Battalion Chief, Director'),
(4, 2, 'Puppy, Soldier, Lieutenant, Mercenary, Captain, General, Veteran, War King, -, -'),
(5, 1, 'Member, Wanna Be, Connectedguy, Familyfriend, Soldier, Capo, Consigliere, Streetboss, Underboss, Boss'),
(5, 2, 'Prospect, Biker, Fresh Member, Member, Treasurer, Enforcer, Sgt at Arms, Vice President, President, President'),
(6, 1, 'Bodyguard, Shatei, Kyodai, Wakagashira, Sateigashira, Saikokomon, Oyabun, -, -, -'),
(6, 2, 'Ochroniarz, Barman, Starszy Barman, Kierownik Barmanów, Asystent, Vice Kierownik KO, Kierownik KO, -, -, -'),
(7, 1, 'Training Agent, Special Agent I, Special Agent II, Special Agent III, Senior Agent I, Senior Agent II, Supervisory Agent, Assistant SAC, Special Agent I.C., Executive Director'),
(7, 2, 'Wanna-be, Assosicate, Fresh blood, Phantom, Agent, Boss, Former boss, -, -, -'),
(8, 1, 'Operator mopa, Czyściciel noży, Relatywista moralny, Akwizytor eutanazji, Wirtuoz noża, Architekt rzezi, Siewca śmierci, Mistrz zbrodni, -, -'),
(8, 2, 'Włóczęga, Mieszkaniec, -, -, Praktykant, Trener, Kierownik, Zastępca Prezesa, Prezes, -'),
(9, 1, 'Zawieszony, Spiker, Dziennikarz, Prezenter Muzyczny, Reporter, Reporter Śledczy, Redaktor Naczelny, Kierownik, Vice Dyrektor, Dyrektor'),
(9, 2, 'Bollard, Member, Mercenary, Wiseguy, Manager, Underboss, O.G., -, -, -'),
(10, 1, 'Mechanik, Kierowca, Starszy Kierowca, Taksówkarz, Pilot, Kierownik, Zastępca Prezesa, Prezes, -, -'),
(10, 2, 'WANNA-BE, OUTSIDER, FREELANCER, MEMBER, CASHMAKER, LEADER, HEAD, -, -, -'),
(11, 1, 'Legenda, ...., ...., ..., Prokurator Stanowy, Sędzia Najwyższy, Senator, Sekretarz, Z-ca Gubernatora, Gubernator'),
(11, 2, 'Out soldier, Wanna Be, Member, Old member, Young soldier, Soldier, Young captain, Captain, Y.O.G, O.G'),
(12, 1, 'Wanna Be, Member, Diler, Gangster, Capitan, Y.O.G., O.G., -, -, -'),
(12, 2, 'Improver, Entrant Driver, Master Driver, Chaser, Special Chaser, St. Wheel Master, Assistant Boss, Boss, -, -'),
(13, 1, 'Wanna Be, Dealer, Fresh Member, Crackville Member, Old Member, Hood Protector, Captain, Y.O.G., O.G., -'),
(13, 2, 'Praktykant, Sprzątaczka, Dostawca, Przewodnik, Księgowy, Zastępca Prezesa, Prezes, -, -, -'),
(14, 1, 'Novice, Rey, Secretary, Tresurer, Investigator, Crown chairman, Enforcer, Cacique, Inca, The crown'),
(14, 2, 'Mechanic, Young Driver, Driver, Expert Driver, Moto-Driver, Legendary, Vice Leader, Leader, -, -'),
(15, 1, 'Newbie, Member, Young Driver, Expert, Drifter, Legend Driver, Right Hand, Drift King, Vice Leader, Leader'),
(15, 2, 'Praktykant, Mechanik, Majster, Koordynator, Brygadzista, Mistrz, Kierownik, Zastępca, Prezes, Właściciel'),
(16, 1, 'Little Dodger, Soldat, Gefreiter, Feldwebel, Leutnant, Rittmeister, Major, General, Fuhrer, -'),
(16, 2, 'Zoltodziob, Stazysta, Pocz. Mechanik, Mechanik, Dos. Mechanik, Majster, Kierownik, Zastępca Prezesa, Prezes, -'),
(17, 1, 'Candidate, Firefighter, Selectional FF, Fire Officer, Lieutenant, Lieutenant II, Staff Aspirant, Captain, Assistant Brigadier, Brigadier'),
(17, 2, 'Kierowca, Barman, Kasjer, Ochroniarz, DJ, Szef Ochrony, Kierownik, Zastępca Prezesa, Prezes, Pani Prezes'),
(18, 1, '-, -, -, -, -, -, -, -, -, Komandos'),
(18, 2, 'Obsluga, Barman, Ochroniarz, Starszy ochroniarz, DJ, Kierownik ochrony, Kierownik klubu, Vice Prezes, Prezes, -'),
(19, 2, 'Praktykant, Młodszy Mechanik, Lakiernik, Mechanik, Starszy Mechanik, Kierownik, Szef, -, -, -'),
(20, 2, 'Stazysta, Kelner, Kasjer, St. Kasjer, St. Kelner, Kierownik, Szef, -, -, -'),
(21, 2, 'Nowy Kurier, Kurier I, Kurier II, Kurier III, Kurier IV, Król Kurierów, Sprzedawca, Kierownik, Zastepca Prezesa, Prezes'),
(22, 2, 'Nowy kurier, Starszy kurier, Doświadczony kurier, Młodszy Sprzedawca, Sprzedawca, Kierownik, Zastępca Prezesa, Prezes, Właściciel, -'),
(23, 2, 'Ochroniarz, Kurier, Starszy Kurier, Młodszy Sprzedawca, Sprzedawca, Starszy Sprzedawca, Kierownik, Zastępca Prezesa, Prezes, Właściciel'),
(24, 2, 'Recruit, Beggining agent, Agent, Technic, Terrain Agent, Special Agent, YOG, OG, Vice Director, Director'),
(25, 2, 'Pakiet Bronze, Pakiet Silver, Pakiet Gold, Pakiet Platinum, Pakiet Diamond, Pakiet Premium, RAK, -, -, -'),
(26, 2, 'Budowlaniec, -, -, Brygadier, Majster, Architekt, Kierownik budowy, -, -, -'),
(27, 2, 'Dedication, Friend, Novice, Haunted, Fallen, Countess, The Devil, Queen, -, -'),
(28, 2, 'Friend Club, Prospect, Ass Kicker, Road Captain, Treasurer, Secretary, Sgt. at Arms, Vice President, President, -'),
(29, 2, 'Outsider, Member, Wanna Be, Gangster, Hustler, Y.O.G, O.G, -, -, -'),
(30, 2, 'Robol, Starszy robol, Budowlaniec, Leć po wódę, Mietek, Majster, Kierownik, -, -, -'),
(31, 2, 'Sta¿ysta, Kelner, Kasjer, St. Kasjer, St. Kelner, Kierownik, Szef, O.G, -, -'),
(32, 2, '-, Trainee Agent I, Traine Agent II, Master Trainee, Agent-in-Charge, -, -, -, -, -'),
(33, 2, 'Recrut 0, Recrut 1, Recrut 2, Recrut 3, Recrut 4, Special Agent I, Special Agent II, -, -, -'),
(34, 2, 'Outsider, Wanna Be, Associate, Soldier, Captain, Underboss, Boss, -, -, -'),
(35, 2, 'Mechanic, Young Driver, Driver, Tuner, Experienced Driver, Driver Legend, Wolf King, Leader, -, -'),
(36, 2, 'Wanna Be, Pracownik, Zolnierz, Kapitan, Podszef, Doradca, Szef, -, -, -'),
(37, 2, 'Wanna Be, Watts Dweller, Dealer, Member, Gangbanger, Y.O.G., O.G., -, -, -'),
(38, 2, 'Noname, Wannabe, Nicpoń, Gniewny, Rozrabiaka, Drifter, Drift Master, Boss, -, -'),
(39, 2, 'Niewolnik, Wieśniak, Farmer, Kmieć, Zastępca gospodarza, Gospodarz, Gospodyni, -, -, -'),
(40, 2, 'Employer, Wanna Be, Associate, Soldier, Captain, Vice Boss, Boss, -, -, -'),
(41, 2, 'Gaijin, Bodigado, Heishi|, Himitsu-no, Maneja, Manejamein, Direkuta, Supabaiza, Saiko-komon, Oyabun'),
(42, 2, 'Outsider, Baby Gangster, Member, Old member, Dealer, Dope Dealer, Y.O.G, O.G, -, -'),
(43, 2, 'Wanna Be, Soldier, Soldier, Soldier, Captain, Y.O.G, O.G, -, -, -'),
(45, 2, 'Wanna-Be, Member, Homie, Drug Diler, Y.O.G, O.G, -, -, -, -');
