#include "cmd\a.pwn"
#include "cmd\addcar.pwn"
#include "cmd\adds.pwn"
#include "cmd\addshelp.pwn"
#include "cmd\adminajail.pwn"
#include "cmd\adminduty.pwn"
#include "cmd\admini.pwn"
#include "cmd\adminstats.pwn"
#include "cmd\ah.pwn"
#include "cmd\akceptuj.pwn"
#include "cmd\alarm.pwn"
#include "cmd\alkomat.pwn"
#include "cmd\ann.pwn"
#include "cmd\antybh.pwn"
#include "cmd\anuluj.pwn"
#include "cmd\anulujzp.pwn"
#include "cmd\app.pwn"
#include "cmd\apteczka.pwn"
#include "cmd\aresztuj.pwn"
#include "cmd\armia.pwn"
#include "cmd\armor.pwn"
#include "cmd\atakuj.pwn"
#include "cmd\autok.pwn"
#include "cmd\autoranny.pwn"
#include "cmd\awans.pwn"
#include "cmd\b.pwn"
#include "cmd\balans.pwn"
#include "cmd\ban.pwn"
#include "cmd\bandana.pwn"
#include "cmd\banip.pwn"
#include "cmd\barierka.pwn"
#include "cmd\basenstats.pwn"
#include "cmd\bdaj.pwn"
#include "cmd\biegnij.pwn"
#include "cmd\bigears.pwn"
#include "cmd\bizinfo.pwn"
#include "cmd\bizlock.pwn"
#include "cmd\bizmoneydebug.pwn"
#include "cmd\biznespomoc.pwn"
#include "cmd\blackjack.pwn"
#include "cmd\blok.pwn"
#include "cmd\blokujnews.pwn"
#include "cmd\blokujnoba.pwn"
#include "cmd\blokujsprzedarz.pwn"
#include "cmd\boks.pwn"
#include "cmd\boksstats.pwn"
#include "cmd\bonehead.pwn"
#include "cmd\boombox.pwn"
#include "cmd\bp.pwn"
#include "cmd\brama.pwn"
#include "cmd\bus.pwn"
#include "cmd\bwsettings.pwn"
#include "cmd\bwtime.pwn"
#include "cmd\c.pwn"
#include "cmd\caluj.pwn"
#include "cmd\car.pwn"
#include "cmd\carhelp.pwn"
#include "cmd\carjump.pwn"
#include "cmd\carslot.pwn"
#include "cmd\cbradio.pwn"
#include "cmd\cca.pwn"
#include "cmd\cennik.pwn"
#include "cmd\check.pwn"
#include "cmd\checkadminstats.pwn"
#include "cmd\checkcar.pwn"
#include "cmd\checkcars.pwn"
#include "cmd\choroba.pwn"
#include "cmd\clearwlall.pwn"
#include "cmd\clearzone.pwn"
#include "cmd\cmdinfo.pwn"
#include "cmd\cnn.pwn"
#include "cmd\cnnn.pwn"
#include "cmd\cp.pwn"
#include "cmd\cp_usun.pwn"
#include "cmd\crimereport.pwn"
#include "cmd\cwarsztat.pwn"
#include "cmd\cygaro.pwn"
#include "cmd\czas.pwn"
#include "cmd\cziterzy.pwn"
#include "cmd\czyjtonumer.pwn"
#include "cmd\czysc.pwn"
#include "cmd\dajbilet.pwn"
#include "cmd\dajbiznes.pwn"
#include "cmd\dajdowozu.pwn"
#include "cmd\dajdzwiek.pwn"
#include "cmd\dajfiltr.pwn"
#include "cmd\dajkase.pwn"
#include "cmd\dajklucze.pwn"
#include "cmd\dajkm.pwn"
#include "cmd\dajkp.pwn"
#include "cmd\dajlideraorg.pwn"
#include "cmd\dajneony.pwn"
#include "cmd\dajpodatek.pwn"
#include "cmd\dajpomocnika.pwn"
#include "cmd\dajrange.pwn"
#include "cmd\dajskryptera.pwn"
#include "cmd\dajzaufanego.pwn"
#include "cmd\datek.pwn"
#include "cmd\degraduj.pwn"
#include "cmd\delete3dtext.pwn"
#include "cmd\deletedom.pwn"
#include "cmd\deleteobject.pwn"
#include "cmd\demorgan.pwn"
#include "cmd\departament.pwn"
#include "cmd\depo.pwn"
#include "cmd\disabletruckerjob.pwn"
#include "cmd\dl.pwn"
#include "cmd\dn.pwn"
#include "cmd\dnobiekt.pwn"
#include "cmd\do.pwn"
#include "cmd\dodajweryfikacje.pwn"
#include "cmd\dolacz.pwn"
#include "cmd\domint.pwn"
#include "cmd\dopasuj.pwn"
#include "cmd\dpa.pwn"
#include "cmd\dr.pwn"
#include "cmd\dskill.pwn"
#include "cmd\dsus.pwn"
#include "cmd\dutycd.pwn"
#include "cmd\dutymoto.pwn"
#include "cmd\dzwon.pwn"
#include "cmd\editobject.pwn"
#include "cmd\edytuj.pwn"
#include "cmd\edytujupr.pwn"
#include "cmd\elo.pwn"
#include "cmd\elo2.pwn"
#include "cmd\endround.pwn"
#include "cmd\entercar.pwn"
#include "cmd\fbidrzwi.pwn"
#include "cmd\fdaj.pwn"
#include "cmd\federalne.pwn"
#include "cmd\felga.pwn"
#include "cmd\felgi.pwn"
#include "cmd\finfo.pwn"
#include "cmd\finisz.pwn"
#include "cmd\fixallveh.pwn"
#include "cmd\fixr.pwn"
#include "cmd\fixveh.pwn"
#include "cmd\flip.pwn"
#include "cmd\fly.pwn"
#include "cmd\fooc.pwn"
#include "cmd\forceskin.pwn"
#include "cmd\forum.pwn"
#include "cmd\fskin.pwn"
#include "cmd\funiadajadmina.pwn"
#include "cmd\gangzone.pwn"
#include "cmd\getcar.pwn"
#include "cmd\gethere.pwn"
#include "cmd\getint.pwn"
#include "cmd\getposp.pwn"
#include "cmd\getvw.pwn"
#include "cmd\givegun.pwn"
#include "cmd\giveroom.pwn"
#include "cmd\glosnik.pwn"
#include "cmd\glosowanie.pwn"
#include "cmd\glosuja.pwn"
#include "cmd\gokarty.pwn"
#include "cmd\goto.pwn"
#include "cmd\gotoadmin.pwn"
#include "cmd\gotobank.pwn"
#include "cmd\gotobiz.pwn"
#include "cmd\gotocar.pwn"
#include "cmd\gotoczit.pwn"
#include "cmd\gotoin.pwn"
#include "cmd\gotoint.pwn"
#include "cmd\gotojet.pwn"
#include "cmd\gotols.pwn"
#include "cmd\gotolv.pwn"
#include "cmd\gotomark.pwn"
#include "cmd\gotomechy.pwn"
#include "cmd\gotopos.pwn"
#include "cmd\gotosalon.pwn"
#include "cmd\gotosf.pwn"
#include "cmd\gotostacja.pwn"
#include "cmd\gotostad.pwn"
#include "cmd\gotoszpital.pwn"
#include "cmd\gotowane.pwn"
#include "cmd\gps.pwn"
#include "cmd\graj.pwn"
#include "cmd\house.pwn"
#include "cmd\houseinfo.pwn"
#include "cmd\houseowner.pwn"
#include "cmd\hpall.pwn"
#include "cmd\hydraulika.pwn"
#include "cmd\i.pwn"
#include "cmd\ibiza.pwn"
#include "cmd\icons.pwn"
#include "cmd\id.pwn"
#include "cmd\idz.pwn"
#include "cmd\innyspawn.pwn"
#include "cmd\ip.pwn"
#include "cmd\irc.pwn"
#include "cmd\ircpomoc.pwn"
#include "cmd\ja.pwn"
#include "cmd\jail.pwn"
#include "cmd\jump.pwn"
#include "cmd\k.pwn"
#include "cmd\kajdanki.pwn"
#include "cmd\kamera.pwn"
#include "cmd\kamerau.pwn"
#include "cmd\kamera_wiezienie.pwn"
#include "cmd\kamizelka.pwn"
#include "cmd\kanister.pwn"
#include "cmd\kasa.pwn"
#include "cmd\kaucja.pwn"
#include "cmd\kb.pwn"
#include "cmd\kick.pwn"
#include "cmd\kickall.pwn"
#include "cmd\kill.pwn"
#include "cmd\killall.pwn"
#include "cmd\kod.pwn"
#include "cmd\kogut.pwn"
#include "cmd\kolejka.pwn"
#include "cmd\kolo.pwn"
#include "cmd\kolory.pwn"
#include "cmd\komandos.pwn"
#include "cmd\komenda.pwn"
#include "cmd\komendy.pwn"
#include "cmd\komentuj.pwn"
#include "cmd\komunikat.pwn"
#include "cmd\konsola.pwn"
#include "cmd\kontakty.pwn"
#include "cmd\kontrakt.pwn"
#include "cmd\kostka.pwn"
#include "cmd\kostka2.pwn"
#include "cmd\koxubankot.pwn"
#include "cmd\kradnij.pwn"
#include "cmd\ksam.pwn"
#include "cmd\ksiazkatel.pwn"
#include "cmd\kup.pwn"
#include "cmd\kuparmor.pwn"
#include "cmd\kupbiletpociag.pwn"
#include "cmd\kupbron.pwn"
#include "cmd\kupdildo.pwn"
#include "cmd\kuphelikopter.pwn"
#include "cmd\kupkredyty.pwn"
#include "cmd\kuplodzie.pwn"
#include "cmd\kupneony.pwn"
#include "cmd\kupowaniedomu.pwn"
#include "cmd\kuppojazd.pwn"
#include "cmd\kupsamoloty.pwn"
#include "cmd\kupskin.pwn"
#include "cmd\kurs.pwn"
#include "cmd\kurtka.pwn"
#include "cmd\laptop.pwn"
#include "cmd\licencje.pwn"
#include "cmd\liderpomoc.pwn"
#include "cmd\lina.pwn"
#include "cmd\linie.pwn"
#include "cmd\loadcommands.pwn"
#include "cmd\loadconfig.pwn"
#include "cmd\loadinfo.pwn"
#include "cmd\lock.pwn"
#include "cmd\lockint.pwn"
#include "cmd\losowostworzdom.pwn"
#include "cmd\losowypozar.pwn"
#include "cmd\lot.pwn"
#include "cmd\lotto.pwn"
#include "cmd\lsmcelevator.pwn"
#include "cmd\makeircadmin.pwn"
#include "cmd\makeleader.pwn"
#include "cmd\makemember.pwn"
#include "cmd\makewomanleader.pwn"
#include "cmd\malunek.pwn"
#include "cmd\malunki.pwn"
#include "cmd\mandacik.pwn"
#include "cmd\marcepan.pwn"
#include "cmd\mark.pwn"
#include "cmd\maska.pwn"
#include "cmd\materialy.pwn"
#include "cmd\mdc.pwn"
#include "cmd\megafon.pwn"
#include "cmd\mi.pwn"
#include "cmd\mikser.pwn"
#include "cmd\mojeauta.pwn"
#include "cmd\mojskin.pwn"
#include "cmd\mole.pwn"
#include "cmd\mp3.pwn"
#include "cmd\msgbox.pwn"
#include "cmd\muzyczka.pwn"
#include "cmd\namierz.pwn"
#include "cmd\napraw.pwn"
#include "cmd\naprawskin.pwn"
#include "cmd\nastepnylevel.pwn"
#include "cmd\naucz.pwn"
#include "cmd\nazywo.pwn"
#include "cmd\newbie.pwn"
#include "cmd\newcar.pwn"
#include "cmd\news.pwn"
#include "cmd\noa.pwn"
#include "cmd\nonewbie.pwn"
#include "cmd\noooc.pwn"
#include "cmd\nos.pwn"
#include "cmd\o.pwn"
#include "cmd\obezwladnij.pwn"
#include "cmd\ochrona.pwn"
#include "cmd\oczyscmdc.pwn"
#include "cmd\od.pwn"
#include "cmd\odmroz.pwn"
#include "cmd\odmv.pwn"
#include "cmd\odpal.pwn"
#include "cmd\odznaka.pwn"
#include "cmd\og.pwn"
#include "cmd\okienko.pwn"
#include "cmd\oldcar.pwn"
#include "cmd\opis.pwn"
#include "cmd\opispomoc.pwn"
#include "cmd\opuscdom.pwn"
#include "cmd\organizacje.pwn"
#include "cmd\otworzlinie.pwn"
#include "cmd\owarsztat.pwn"
#include "cmd\paj.pwn"
#include "cmd\paka.pwn"
#include "cmd\pakietmrucznika.pwn"
#include "cmd\paliwo.pwn"
#include "cmd\panel.pwn"
#include "cmd\panelbasenu.pwn"
#include "cmd\paralizuj.pwn"
#include "cmd\patrol.pwn"
#include "cmd\pban.pwn"
#include "cmd\pblok.pwn"
#include "cmd\piwo.pwn"
#include "cmd\pjtest.pwn"
#include "cmd\pl.pwn"
#include "cmd\plac.pwn"
#include "cmd\placmedyk.pwn"
#include "cmd\po.pwn"
#include "cmd\pobij.pwn"
#include "cmd\podatek.pwn"
#include "cmd\poddajesie.pwn"
#include "cmd\poddajsie.pwn"
#include "cmd\poddajsie2.pwn"
#include "cmd\podglad.pwn"
#include "cmd\podszyjsie.pwn"
#include "cmd\pogoda.pwn"
#include "cmd\pogodaall.pwn"
#include "cmd\pojazdygracza.pwn"
#include "cmd\pokazcb.pwn"
#include "cmd\pokazdowod.pwn"
#include "cmd\polej.pwn"
#include "cmd\pomoc2.pwn"
#include "cmd\pomocdom.pwn"
#include "cmd\poscig.pwn"
#include "cmd\pozwolenie.pwn"
#include "cmd\pr.pwn"
#include "cmd\pracownicy.pwn"
#include "cmd\premium.pwn"
#include "cmd\premiumskin.pwn"
#include "cmd\przebierz.pwn"
#include "cmd\przejazd.pwn"
#include "cmd\przelew.pwn"
#include "cmd\przeszukaj.pwn"
#include "cmd\przyjmij.pwn"
#include "cmd\pwarn.pwn"
#include "cmd\qf.pwn"
#include "cmd\quitpraca.pwn"
#include "cmd\r.pwn"
#include "cmd\radiostacja.pwn"
#include "cmd\ranny.pwn"
#include "cmd\rapidfly.pwn"
#include "cmd\raport.pwn"
#include "cmd\re.pwn"
#include "cmd\reflektor.pwn"
#include "cmd\reklama.pwn"
#include "cmd\reloadbans.pwn"
#include "cmd\removecar.pwn"
#include "cmd\removeganglimit.pwn"
#include "cmd\removezoneprotect.pwn"
#include "cmd\rentroom.pwn"
#include "cmd\resetsejfhasla.pwn"
#include "cmd\reset_ulepszen.pwn"
#include "cmd\resms.pwn"
#include "cmd\respawn.pwn"
#include "cmd\respawncar.pwn"
#include "cmd\respawnplayer.pwn"
#include "cmd\restart.pwn"
#include "cmd\rezonans.pwn"
#include "cmd\rodzinaskrypt.pwn"
#include "cmd\rodzinny.pwn"
#include "cmd\roleta.pwn"
#include "cmd\rooc.pwn"
#include "cmd\rozkuj.pwn"
#include "cmd\rozwiaz.pwn"
#include "cmd\rozwiedz.pwn"
#include "cmd\rozwod.pwn"
#include "cmd\ruleta.pwn"
#include "cmd\ryby.pwn"
#include "cmd\rybypomoc.pwn"
#include "cmd\sad.pwn"
#include "cmd\say.pwn"
#include "cmd\sb.pwn"
#include "cmd\sban.pwn"
#include "cmd\sblok.pwn"
#include "cmd\scena.pwn"
#include "cmd\scenaallow.pwn"
#include "cmd\scenadisallow.pwn"
#include "cmd\sejffrakcja.pwn"
#include "cmd\sejfpomoc.pwn"
#include "cmd\sejfrodzina.pwn"
#include "cmd\selldom.pwn"
#include "cmd\setac.pwn"
#include "cmd\setarmor.pwn"
#include "cmd\setcarint.pwn"
#include "cmd\setcarvw.pwn"
#include "cmd\setint.pwn"
#include "cmd\setmats.pwn"
#include "cmd\setmc.pwn"
#include "cmd\setname.pwn"
#include "cmd\setplocal.pwn"
#include "cmd\setskin.pwn"
#include "cmd\setslot.pwn"
#include "cmd\setstat.pwn"
#include "cmd\setstrong.pwn"
#include "cmd\setteam.pwn"
#include "cmd\setveh.pwn"
#include "cmd\setvw.pwn"
#include "cmd\setzonecontrol.pwn"
#include "cmd\sex.pwn"
#include "cmd\sh.pwn"
#include "cmd\showkary.pwn"
#include "cmd\skick.pwn"
#include "cmd\skill.pwn"
#include "cmd\skille.pwn"
#include "cmd\skinf.pwn"
#include "cmd\skiny.pwn"
#include "cmd\skret.pwn"
#include "cmd\skydive.pwn"
#include "cmd\slap.pwn"
#include "cmd\slub.pwn"
#include "cmd\sluzba.pwn"
#include "cmd\sms.pwn"
#include "cmd\snn.pwn"
#include "cmd\spec.pwn"
#include "cmd\spoiler.pwn"
#include "cmd\spoilery.pwn"
#include "cmd\sprawdzdom.pwn"
#include "cmd\sprawdzgwiazdki.pwn"
#include "cmd\sprawdzin.pwn"
#include "cmd\sprawdzinv.pwn"
#include "cmd\sprawdzkase.pwn"
#include "cmd\sprawdzkredyty.pwn"
#include "cmd\sprawdzneon.pwn"
#include "cmd\sprawdzteam.pwn"
#include "cmd\sprawdztest.pwn"
#include "cmd\sprobuj.pwn"
#include "cmd\sprunk.pwn"
#include "cmd\sprzedajalkohol.pwn"
#include "cmd\sprzedajauto.pwn"
#include "cmd\sprzedajbilet.pwn"
#include "cmd\sprzedajbiznes.pwn"
#include "cmd\sprzedajbron.pwn"
#include "cmd\sprzedajmaterialy.pwn"
#include "cmd\sprzedajnarkotyki.pwn"
#include "cmd\sprzedajrybe.pwn"
#include "cmd\stanowe.pwn"
#include "cmd\startlotto.pwn"
#include "cmd\startujlekcje.pwn"
#include "cmd\staty.pwn"
#include "cmd\stazer.pwn"
#include "cmd\stopanim.pwn"
#include "cmd\stopbieg.pwn"
#include "cmd\streamer.pwn"
#include "cmd\studia.pwn"
#include "cmd\stworz.pwn"
#include "cmd\stworzdom.pwn"
#include "cmd\stworzobiekty.pwn"
#include "cmd\stworztrase.pwn"
#include "cmd\supportduty.pwn"
#include "cmd\swat.pwn"
#include "cmd\swiadek.pwn"
#include "cmd\szept.pwn"
#include "cmd\szturmowy.pwn"
#include "cmd\szukani.pwn"
#include "cmd\tablet.pwn"
#include "cmd\tankowanie.pwn"
#include "cmd\tankujauta.pwn"
#include "cmd\tankveh.pwn"
#include "cmd\taryfikator.pwn"
#include "cmd\tazer.pwn"
#include "cmd\teczka.pwn"
#include "cmd\telefonpomoc.pwn"
#include "cmd\teleturniej.pwn"
#include "cmd\temat.pwn"
#include "cmd\ticketend.pwn"
#include "cmd\tickets.pwn"
#include "cmd\tjdcp1.pwn"
#include "cmd\tjdcp2.pwn"
#include "cmd\tod.pwn"
#include "cmd\togadmin.pwn"
#include "cmd\togadminmess.pwn"
#include "cmd\togcb.pwn"
#include "cmd\togdepo.pwn"
#include "cmd\togfam.pwn"
#include "cmd\togfinfo.pwn"
#include "cmd\toglicznik.pwn"
#include "cmd\togname.pwn"
#include "cmd\togooc.pwn"
#include "cmd\togpodglad.pwn"
#include "cmd\togtxda.pwn"
#include "cmd\togwl.pwn"
#include "cmd\tp.pwn"
#include "cmd\trampolina.pwn"
#include "cmd\trasa.pwn"
#include "cmd\trasy.pwn"
#include "cmd\trasybiegu.pwn"
#include "cmd\ubranie.pwn"
#include "cmd\ucisz.pwn"
#include "cmd\ugotuj.pwn"
#include "cmd\ukradnij.pwn"
#include "cmd\ulecz.pwn"
#include "cmd\uleczmnie.pwn"
#include "cmd\ulepsz.pwn"
#include "cmd\unblock.pwn"
#include "cmd\unbw.pwn"
#include "cmd\undemorgan.pwn"
#include "cmd\unfrakcja.pwn"
#include "cmd\uniform2.pwn"
#include "cmd\unjail.pwn"
#include "cmd\unrentroom.pwn"
#include "cmd\unspec.pwn"
#include "cmd\unwarn.pwn"
#include "cmd\up.pwn"
#include "cmd\uprawnienia.pwn"
#include "cmd\ustawcena.pwn"
#include "cmd\ustawmistrz.pwn"
#include "cmd\usunbron.pwn"
#include "cmd\usunpozar.pwn"
#include "cmd\uwb.pwn"
#include "cmd\veh.pwn"
#include "cmd\vopis.pwn"
#include "cmd\vopispomoc.pwn"
#include "cmd\warn.pwn"
#include "cmd\wczytajrangi.pwn"
#include "cmd\wczytajskiny.pwn"
#include "cmd\wczytajskrypt.pwn"
#include "cmd\wejdz.pwn"
#include "cmd\wejdzw.pwn"
#include "cmd\wez.pwn"
#include "cmd\wezdragi.pwn"
#include "cmd\wezpizze.pwn"
#include "cmd\wezportfel.pwn"
#include "cmd\wezwij.pwn"
#include "cmd\wezwijwoz.pwn"
#include "cmd\wezzlecenie.pwn"
#include "cmd\wiadomosc.pwn"
#include "cmd\wieza.pwn"
#include "cmd\winda.pwn"
#include "cmd\winda2.pwn"
#include "cmd\windalock.pwn"
#include "cmd\witaj.pwn"
#include "cmd\wizytowka.pwn"
#include "cmd\wk.pwn"
#include "cmd\wobiekt.pwn"
#include "cmd\wplac.pwn"
#include "cmd\wrzuc.pwn"
#include "cmd\wtazer.pwn"
#include "cmd\wybieralka.pwn"
#include "cmd\wyczysc.pwn"
#include "cmd\wyjdz.pwn"
#include "cmd\wyjedz.pwn"
#include "cmd\wyloguj.pwn"
#include "cmd\wylogujall.pwn"
#include "cmd\wylogujgracz.pwn"
#include "cmd\wymiana.pwn"
#include "cmd\wynajempomoc.pwn"
#include "cmd\wyniki.pwn"
#include "cmd\wypij.pwn"
#include "cmd\wypisz.pwn"
#include "cmd\wyplac.pwn"
#include "cmd\wyprowadz.pwn"
#include "cmd\wypusc.pwn"
#include "cmd\wypuscrybe.pwn"
#include "cmd\wyrzucbronie.pwn"
#include "cmd\wyscig.pwn"
#include "cmd\wyscig_start.pwn"
#include "cmd\wyscig_stop.pwn"
#include "cmd\wywal.pwn"
#include "cmd\wywalcb.pwn"
#include "cmd\wywaldmv.pwn"
#include "cmd\wywaldragi.pwn"
#include "cmd\wywalmaterialy.pwn"
#include "cmd\wywalrybe.pwn"
#include "cmd\wywalryby.pwn"
#include "cmd\wywaltelefon.pwn"
#include "cmd\wywalzsad.pwn"
#include "cmd\wywaz.pwn"
#include "cmd\yo.pwn"
#include "cmd\yo2.pwn"
#include "cmd\yo3.pwn"
#include "cmd\yo4.pwn"
#include "cmd\z.pwn"
#include "cmd\zabierz.pwn"
#include "cmd\zabierzbiznes.pwn"
#include "cmd\zabierzlideraorg.pwn"
#include "cmd\zablokujtel.pwn"
#include "cmd\zablokujw.pwn"
#include "cmd\zakoncztrase.pwn"
#include "cmd\zakuj.pwn"
#include "cmd\zaliczegz.pwn"
#include "cmd\zamek.pwn"
#include "cmd\zamknijlinie.pwn"
#include "cmd\zamroz.pwn"
#include "cmd\zaparkuj.pwn"
#include "cmd\zapiszdomy.pwn"
#include "cmd\zapiszkonta.pwn"
#include "cmd\zapytaj.pwn"
#include "cmd\zasady.pwn"
#include "cmd\zastrzyk.pwn"
#include "cmd\zatankuj.pwn"
#include "cmd\zatrzymajlekcje.pwn"
#include "cmd\zaufanyggracz.pwn"
#include "cmd\zawodnicy.pwn"
#include "cmd\zawodnik.pwn"
#include "cmd\zaznacz.pwn"
#include "cmd\zbijwl.pwn"
#include "cmd\zbrojuj.pwn"
#include "cmd\zd.pwn"
#include "cmd\zdejmijbpk.pwn"
#include "cmd\zdejmijkevlar.pwn"
#include "cmd\zderzaki.pwn"
#include "cmd\zdmv.pwn"
#include "cmd\zgas.pwn"
#include "cmd\zjedz.pwn"
#include "cmd\zk.pwn"
#include "cmd\zlap.pwn"
#include "cmd\zlomuj.pwn"
#include "cmd\zmiendom.pwn"
#include "cmd\zmiendomk.pwn"
#include "cmd\zmienhaslo.pwn"
#include "cmd\zmienhp.pwn"
#include "cmd\zmiennick.pwn"
#include "cmd\zmienplec.pwn"
#include "cmd\zmienprace.pwn"
#include "cmd\zmienskin.pwn"
#include "cmd\zmienwiek.pwn"
#include "cmd\zmienwl.pwn"
#include "cmd\zniszczobiekty.pwn"
#include "cmd\zobp.pwn"
#include "cmd\zonedelay.pwn"
#include "cmd\zoneid.pwn"
#include "cmd\zrobkolejke.pwn"
#include "cmd\zuzel.pwn"
#include "cmd\zuzel_start.pwn"
#include "cmd\zuzel_stop.pwn"
#include "cmd\zwiaz.pwn"
#include "cmd\zwolnij.pwn"

InitCommands()
{
	command_a();
	command_addcar();
	command_adds();
	command_addshelp();
	command_adminajail();
	command_adminduty();
	command_admini();
	command_adminstats();
	command_ah();
	command_akceptuj();
	command_alarm();
	command_alkomat();
	command_ann();
	command_antybh();
	command_anuluj();
	command_anulujzp();
	command_app();
	command_apteczka();
	command_aresztuj();
	command_armia();
	command_armor();
	command_atakuj();
	command_autok();
	command_autoranny();
	command_awans();
	command_b();
	command_balans();
	command_ban();
	command_bandana();
	command_banip();
	command_barierka();
	command_basenstats();
	command_bdaj();
	command_biegnij();
	command_bigears();
	command_bizinfo();
	command_bizlock();
	command_bizmoneydebug();
	command_biznespomoc();
	command_blackjack();
	command_blok();
	command_blokujnews();
	command_blokujnoba();
	command_blokujsprzedarz();
	command_boks();
	command_boksstats();
	command_bonehead();
	command_boombox();
	command_bp();
	command_brama();
	command_bus();
	command_bwsettings();
	command_bwtime();
	command_c();
	command_caluj();
	command_car();
	command_carhelp();
	command_carjump();
	command_carslot();
	command_cbradio();
	command_cca();
	command_cennik();
	command_check();
	command_checkadminstats();
	command_checkcar();
	command_checkcars();
	command_choroba();
	command_clearwlall();
	command_clearzone();
	command_cmdinfo();
	command_cnn();
	command_cnnn();
	command_cp();
	command_cp_usun();
	command_crimereport();
	command_cwarsztat();
	command_cygaro();
	command_czas();
	command_cziterzy();
	command_czyjtonumer();
	command_czysc();
	command_dajbilet();
	command_dajbiznes();
	command_dajdowozu();
	command_dajdzwiek();
	command_dajfiltr();
	command_dajkase();
	command_dajklucze();
	command_dajkm();
	command_dajkp();
	command_dajlideraorg();
	command_dajneony();
	command_dajpodatek();
	command_dajpomocnika();
	command_dajrange();
	command_dajskryptera();
	command_dajzaufanego();
	command_datek();
	command_degraduj();
	command_delete3dtext();
	command_deletedom();
	command_deleteobject();
	command_demorgan();
	command_departament();
	command_depo();
	command_disabletruckerjob();
	command_dl();
	command_dn();
	command_dnobiekt();
	command_do();
	command_dodajweryfikacje();
	command_dolacz();
	command_domint();
	command_dopasuj();
	command_dpa();
	command_dr();
	command_dskill();
	command_dsus();
	command_dutycd();
	command_dutymoto();
	command_dzwon();
	command_editobject();
	command_edytuj();
	command_edytujupr();
	command_elo();
	command_elo2();
	command_endround();
	command_entercar();
	command_fbidrzwi();
	command_fdaj();
	command_federalne();
	command_felga();
	command_felgi();
	command_finfo();
	command_finisz();
	command_fixallveh();
	command_fixr();
	command_fixveh();
	command_flip();
	command_fly();
	command_fooc();
	command_forceskin();
	command_forum();
	command_fskin();
	command_funiadajadmina();
	command_gangzone();
	command_getcar();
	command_gethere();
	command_getint();
	command_getposp();
	command_getvw();
	command_givegun();
	command_giveroom();
	command_glosnik();
	command_glosowanie();
	command_glosuja();
	command_gokarty();
	command_goto();
	command_gotoadmin();
	command_gotobank();
	command_gotobiz();
	command_gotocar();
	command_gotoczit();
	command_gotoin();
	command_gotoint();
	command_gotojet();
	command_gotols();
	command_gotolv();
	command_gotomark();
	command_gotomechy();
	command_gotopos();
	command_gotosalon();
	command_gotosf();
	command_gotostacja();
	command_gotostad();
	command_gotoszpital();
	command_gotowane();
	command_gps();
	command_graj();
	command_house();
	command_houseinfo();
	command_houseowner();
	command_hpall();
	command_hydraulika();
	command_i();
	command_ibiza();
	command_icons();
	command_id();
	command_idz();
	command_innyspawn();
	command_ip();
	command_irc();
	command_ircpomoc();
	command_ja();
	command_jail();
	command_jump();
	command_k();
	command_kajdanki();
	command_kamera();
	command_kamerau();
	command_kamera_wiezienie();
	command_kamizelka();
	command_kanister();
	command_kasa();
	command_kaucja();
	command_kb();
	command_kick();
	command_kickall();
	command_kill();
	command_killall();
	command_kod();
	command_kogut();
	command_kolejka();
	command_kolo();
	command_kolory();
	command_komandos();
	command_komenda();
	command_komendy();
	command_komentuj();
	command_komunikat();
	command_konsola();
	command_kontakty();
	command_kontrakt();
	command_kostka();
	command_kostka2();
	command_koxubankot();
	command_kradnij();
	command_ksam();
	command_ksiazkatel();
	command_kup();
	command_kuparmor();
	command_kupbiletpociag();
	command_kupbron();
	command_kupdildo();
	command_kuphelikopter();
	command_kupkredyty();
	command_kuplodzie();
	command_kupneony();
	command_kupowaniedomu();
	command_kuppojazd();
	command_kupsamoloty();
	command_kupskin();
	command_kurs();
	command_kurtka();
	command_laptop();
	command_licencje();
	command_liderpomoc();
	command_lina();
	command_linie();
	command_loadcommands();
	command_loadconfig();
	command_loadinfo();
	command_lock();
	command_lockint();
	command_losowostworzdom();
	command_losowypozar();
	command_lot();
	command_lotto();
	command_lsmcelevator();
	command_makeircadmin();
	command_makeleader();
	command_makemember();
	command_makewomanleader();
	command_malunek();
	command_malunki();
	command_mandacik();
	command_marcepan();
	command_mark();
	command_maska();
	command_materialy();
	command_mdc();
	command_megafon();
	command_mi();
	command_mikser();
	command_mojeauta();
	command_mojskin();
	command_mole();
	command_mp3();
	command_msgbox();
	command_muzyczka();
	command_namierz();
	command_napraw();
	command_naprawskin();
	command_nastepnylevel();
	command_naucz();
	command_nazywo();
	command_newbie();
	command_newcar();
	command_news();
	command_noa();
	command_nonewbie();
	command_noooc();
	command_nos();
	command_o();
	command_obezwladnij();
	command_ochrona();
	command_oczyscmdc();
	command_od();
	command_odmroz();
	command_odmv();
	command_odpal();
	command_odznaka();
	command_og();
	command_okienko();
	command_oldcar();
	command_opis();
	command_opispomoc();
	command_opuscdom();
	command_organizacje();
	command_otworzlinie();
	command_owarsztat();
	command_paj();
	command_paka();
	command_pakietmrucznika();
	command_paliwo();
	command_panel();
	command_panelbasenu();
	command_paralizuj();
	command_patrol();
	command_pban();
	command_pblok();
	command_piwo();
	command_pjtest();
	command_pl();
	command_plac();
	command_placmedyk();
	command_po();
	command_pobij();
	command_podatek();
	command_poddajesie();
	command_poddajsie();
	command_poddajsie2();
	command_podglad();
	command_podszyjsie();
	command_pogoda();
	command_pogodaall();
	command_pojazdygracza();
	command_pokazcb();
	command_pokazdowod();
	command_polej();
	command_pomoc2();
	command_pomocdom();
	command_poscig();
	command_pozwolenie();
	command_pr();
	command_pracownicy();
	command_premium();
	command_premiumskin();
	command_przebierz();
	command_przejazd();
	command_przelew();
	command_przeszukaj();
	command_przyjmij();
	command_pwarn();
	command_qf();
	command_quitpraca();
	command_r();
	command_radiostacja();
	command_ranny();
	command_rapidfly();
	command_raport();
	command_re();
	command_reflektor();
	command_reklama();
	command_reloadbans();
	command_removecar();
	command_removeganglimit();
	command_removezoneprotect();
	command_rentroom();
	command_resetsejfhasla();
	command_reset_ulepszen();
	command_resms();
	command_respawn();
	command_respawncar();
	command_respawnplayer();
	command_restart();
	command_rezonans();
	command_rodzinaskrypt();
	command_rodzinny();
	command_roleta();
	command_rooc();
	command_rozkuj();
	command_rozwiaz();
	command_rozwiedz();
	command_rozwod();
	command_ruleta();
	command_ryby();
	command_rybypomoc();
	command_sad();
	command_say();
	command_sb();
	command_sban();
	command_sblok();
	command_scena();
	command_scenaallow();
	command_scenadisallow();
	command_sejffrakcja();
	command_sejfpomoc();
	command_sejfrodzina();
	command_selldom();
	command_setac();
	command_setarmor();
	command_setcarint();
	command_setcarvw();
	command_setint();
	command_setmats();
	command_setmc();
	command_setname();
	command_setplocal();
	command_setskin();
	command_setslot();
	command_setstat();
	command_setstrong();
	command_setteam();
	command_setveh();
	command_setvw();
	command_setzonecontrol();
	command_sex();
	command_sh();
	command_showkary();
	command_skick();
	command_skill();
	command_skille();
	command_skinf();
	command_skiny();
	command_skret();
	command_skydive();
	command_slap();
	command_slub();
	command_sluzba();
	command_sms();
	command_snn();
	command_spec();
	command_spoiler();
	command_spoilery();
	command_sprawdzdom();
	command_sprawdzgwiazdki();
	command_sprawdzin();
	command_sprawdzinv();
	command_sprawdzkase();
	command_sprawdzkredyty();
	command_sprawdzneon();
	command_sprawdzteam();
	command_sprawdztest();
	command_sprobuj();
	command_sprunk();
	command_sprzedajalkohol();
	command_sprzedajauto();
	command_sprzedajbilet();
	command_sprzedajbiznes();
	command_sprzedajbron();
	command_sprzedajmaterialy();
	command_sprzedajnarkotyki();
	command_sprzedajrybe();
	command_stanowe();
	command_startlotto();
	command_startujlekcje();
	command_staty();
	command_stazer();
	command_stopanim();
	command_stopbieg();
	command_streamer();
	command_studia();
	command_stworz();
	command_stworzdom();
	command_stworzobiekty();
	command_stworztrase();
	command_supportduty();
	command_swat();
	command_swiadek();
	command_szept();
	command_szturmowy();
	command_szukani();
	command_tablet();
	command_tankowanie();
	command_tankujauta();
	command_tankveh();
	command_taryfikator();
	command_tazer();
	command_teczka();
	command_telefonpomoc();
	command_teleturniej();
	command_temat();
	command_ticketend();
	command_tickets();
	command_tjdcp1();
	command_tjdcp2();
	command_tod();
	command_togadmin();
	command_togadminmess();
	command_togcb();
	command_togdepo();
	command_togfam();
	command_togfinfo();
	command_toglicznik();
	command_togname();
	command_togooc();
	command_togpodglad();
	command_togtxda();
	command_togwl();
	command_tp();
	command_trampolina();
	command_trasa();
	command_trasy();
	command_trasybiegu();
	command_ubranie();
	command_ucisz();
	command_ugotuj();
	command_ukradnij();
	command_ulecz();
	command_uleczmnie();
	command_ulepsz();
	command_unblock();
	command_unbw();
	command_undemorgan();
	command_unfrakcja();
	command_uniform2();
	command_unjail();
	command_unrentroom();
	command_unspec();
	command_unwarn();
	command_up();
	command_uprawnienia();
	command_ustawcena();
	command_ustawmistrz();
	command_usunbron();
	command_usunpozar();
	command_uwb();
	command_veh();
	command_vopis();
	command_vopispomoc();
	command_warn();
	command_wczytajrangi();
	command_wczytajskiny();
	command_wczytajskrypt();
	command_wejdz();
	command_wejdzw();
	command_wez();
	command_wezdragi();
	command_wezpizze();
	command_wezportfel();
	command_wezwij();
	command_wezwijwoz();
	command_wezzlecenie();
	command_wiadomosc();
	command_wieza();
	command_winda();
	command_winda2();
	command_windalock();
	command_witaj();
	command_wizytowka();
	command_wk();
	command_wobiekt();
	command_wplac();
	command_wrzuc();
	command_wtazer();
	command_wybieralka();
	command_wyczysc();
	command_wyjdz();
	command_wyjedz();
	command_wyloguj();
	command_wylogujall();
	command_wylogujgracz();
	command_wymiana();
	command_wynajempomoc();
	command_wyniki();
	command_wypij();
	command_wypisz();
	command_wyplac();
	command_wyprowadz();
	command_wypusc();
	command_wypuscrybe();
	command_wyrzucbronie();
	command_wyscig();
	command_wyscig_start();
	command_wyscig_stop();
	command_wywal();
	command_wywalcb();
	command_wywaldmv();
	command_wywaldragi();
	command_wywalmaterialy();
	command_wywalrybe();
	command_wywalryby();
	command_wywaltelefon();
	command_wywalzsad();
	command_wywaz();
	command_yo();
	command_yo2();
	command_yo3();
	command_yo4();
	command_z();
	command_zabierz();
	command_zabierzbiznes();
	command_zabierzlideraorg();
	command_zablokujtel();
	command_zablokujw();
	command_zakoncztrase();
	command_zakuj();
	command_zaliczegz();
	command_zamek();
	command_zamknijlinie();
	command_zamroz();
	command_zaparkuj();
	command_zapiszdomy();
	command_zapiszkonta();
	command_zapytaj();
	command_zasady();
	command_zastrzyk();
	command_zatankuj();
	command_zatrzymajlekcje();
	command_zaufanyggracz();
	command_zawodnicy();
	command_zawodnik();
	command_zaznacz();
	command_zbijwl();
	command_zbrojuj();
	command_zd();
	command_zdejmijbpk();
	command_zdejmijkevlar();
	command_zderzaki();
	command_zdmv();
	command_zgas();
	command_zjedz();
	command_zk();
	command_zlap();
	command_zlomuj();
	command_zmiendom();
	command_zmiendomk();
	command_zmienhaslo();
	command_zmienhp();
	command_zmiennick();
	command_zmienplec();
	command_zmienprace();
	command_zmienskin();
	command_zmienwiek();
	command_zmienwl();
	command_zniszczobiekty();
	command_zobp();
	command_zonedelay();
	command_zoneid();
	command_zrobkolejke();
	command_zuzel();
	command_zuzel_start();
	command_zuzel_stop();
	command_zwiaz();
	command_zwolnij();
}
