/*
 * 
 *     Colors
 *     © Copyright 2006, 50p
 * 
 */

#if defined _colors_included
	#endinput
#endif
#define _colors_included

#define BEZOWY 0xFFFFADAA
#define BIALY 0xFFFFFFAA
#define BLEKITNY 0x00FFFFAA
#define BORDOWY 0x99001FAA
#define BRAZOWY 0x997A00AA
#define CIEMNY_ZIELONY 0x336633AA
#define CZARNY 0x000000AA
#define CZERWONY 0xFF0000AA
#define FIOLETOWY 0x9E3DFFAA
#define NIEBIESKI 0x0000FFAA
#define POMARANCZOWY 0xFF8000AA
#define ROZOWY 0xFF66CCAA
#define SZARY 0xB0B0B0AA
#define ZIELONY 0x00CC00AA
#define ZOLTY 0xFFFF00AA
