/*
 *
 *     Weapons
 *     © Copyright 2006, 50p
 *
 */

#if defined _weapons_include
	#endinput
#endif
#define _weapons_included

// PICKUPs
#define P_GOLF 333
#define P_PALKA 334
#define P_NOZ 335
#define P_BASEBALL 336
#define P_LOPATA 337
#define P_BILLARD 338
#define P_KATANA 339
#define P_PILA 341
#define P_DILDO1 321
#define P_DILDO2 322
#define P_VIBRATOR1 323
#define P_VIBRATOR2 324
#define P_KWIATY 325
#define P_LASKA 326
#define P_SPADOCHRON 371
#define P_GRANAT 342
#define P_GRANAT_LZAWIACY 343
#define P_MOLOTOV 344
#define P_PISTOL 346
#define P_PISTOL_TLUMIK 347
#define P_DEAGLE 348
#define P_SHOTGUN 349
#define P_SAWN_OFF 350
#define P_COMBAT 351
#define P_MICRO_UZI 352
#define P_TEC9 372
#define P_MP5 353
#define P_AK47 355
#define P_M4 356
#define P_STRZELBA 357
#define P_MIOTACZ_OGNIA 361
#define P_MINIGUN 362
#define P_C4 363
#define P_SPRAY 365
#define P_GASNICA 366
#define P_APARAT 367
#define P_GOOGLE_TERM 368
#define P_GOOGLE_CZERW 369
#define P_JETPACK 370
#define P_SERCE 1240
#define P_KAMIZELKA 1242
#define P_PIGULKA 1241

// Weapons
#define W_PIESC 0
#define W_KASTET 1 // N/A
#define W_GOLF 2
#define W_PALKA 3
#define W_NOZ 4
#define W_BASEBALL 5
#define W_LOPATA 6
#define W_BILARD 7
#define W_KATANA 8
#define W_PILA 9
#define W_DILDO1 10
#define W_DILDO2 11
#define W_VIBRATOR1 12
#define W_VIBRATOR2 13
#define W_KWIATY 14
#define W_LASKA 15
#define W_GRANAT 16
#define W_GRANAT_LZAWIACY 17 // N/A
#define W_MOLOTOV 18 // N/A
// 19 N/A
// 20 N/A
// 21 N/A
#define W_PISTOL 22
#define W_PISTOL_TLUMIK 23
#define W_DEAGLE 24
#define W_SHOTGUN 25
#define W_SAWN_OFF 26
#define W_COMBAT 27
#define W_MICRO_UZI 28
#define W_MP5 29
#define W_AK47 30
#define W_M4 31
#define W_TEC9 32
#define W_STRZELBA 33
#define W_SNIPERKA 34 // N/A
// 35 N/A
// 36 N/A
#define W_MIOTACZ_OGNIA 37
#define W_MINIGUN 38
#define W_C4 39
#define W_DETONATOR 40
#define W_SPRAY 41
#define W_GASNICA 42
#define W_APARAT 43
#define W_GOOGLE_NIGHT 44 // N/A
#define W_GOOGLE_TERM 45 // N/A
#define W_SPADOCHRON 46

